
//+------------------------------------------------------------------+
//|                                                     SuperTrendRSI.mq5 |
//|                                        Generated by ChatGPT          |
//+------------------------------------------------------------------+
#property copyright "ChatGPT"
#property version   "1.00"
#property strict

#include <Trade/Trade.mqh>
#include <Trade/PositionInfo.mqh>

CTrade trade;

//--- input parameters
input int    ATR_Period        = 10;
input double ATR_Multiplier    = 3.0;
input int    RSI_Period        = 14;
input double RSI_BuyLevel      = 55.0;
input double RSI_SellLevel     = 45.0;
input ENUM_TIMEFRAMES TimeFrame = PERIOD_CURRENT;
input double LotsFactor        = 0.01;
input bool   UseFixedLots      = true;
input double FixedLots         = 0.10;
input bool   AllowBuy          = true;
input bool   AllowSell         = true;
input int    MagicNumber       = 12345;
input double TakeProfit_Pips   = 100.0;
input double FixedStopLoss_Pips= 50.0;
input bool   UseTrailing       = true;
input double TrailingStartPoints = 50;
input double TrailingStepPoints  = 20;

//--- global variables
double atrValue;
double supertrend[];
bool trendUp[];

//+------------------------------------------------------------------+
//| Calculate ATR                                                    |
//+------------------------------------------------------------------+
double ATR(int period)
{
   return iATR(_Symbol, TimeFrame, period, 0);
}

//+------------------------------------------------------------------+
//| Compute SuperTrend                                               |
//+------------------------------------------------------------------+
void ComputeSuperTrend(bool &trendUpOut, double &stValueOut)
{
   int bars = 3;
   ArrayResize(supertrend, bars);
   ArrayResize(trendUp, bars);

   double atr = ATR(ATR_Period);
   double hl2 = (iHigh(_Symbol, TimeFrame, 1) + iLow(_Symbol, TimeFrame, 1)) / 2.0;

   static double prevUpper = 0.0;
   static double prevLower = 0.0;
   static bool prevTrendUp = true;

   double upperBand = hl2 + ATR_Multiplier * atr;
   double lowerBand = hl2 - ATR_Multiplier * atr;

   if(upperBand < prevUpper || iClose(_Symbol, TimeFrame, 1) > prevUpper)
      upperBand = prevUpper;
   if(lowerBand > prevLower || iClose(_Symbol, TimeFrame, 1) < prevLower)
      lowerBand = prevLower;

   bool currTrendUp = prevTrendUp;

   if(iClose(_Symbol, TimeFrame, 1) > prevUpper)
      currTrendUp = true;
   else if(iClose(_Symbol, TimeFrame, 1) < prevLower)
      currTrendUp = false;
   else
      currTrendUp = prevTrendUp;

   double stValue = currTrendUp ? lowerBand : upperBand;

   prevUpper = upperBand;
   prevLower = lowerBand;
   prevTrendUp = currTrendUp;

   trendUpOut = currTrendUp;
   stValueOut = stValue;
}

//+------------------------------------------------------------------+
//| RSI Buy condition                                                |
//+------------------------------------------------------------------+
bool RSI_BuyCondition()
{
   double rsi = iRSI(_Symbol, TimeFrame, RSI_Period, PRICE_CLOSE, 0);
   return (rsi > RSI_BuyLevel);
}

//+------------------------------------------------------------------+
//| RSI Sell condition                                               |
//+------------------------------------------------------------------+
bool RSI_SellCondition()
{
   double rsi = iRSI(_Symbol, TimeFrame, RSI_Period, PRICE_CLOSE, 0);
   return (rsi < RSI_SellLevel);
}

//+------------------------------------------------------------------+
//| Normalize lot size                                               |
//+------------------------------------------------------------------+
double NormalizeVolume(double lots)
{
   double volMin  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double volMax  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double volStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lots = MathMax(lots, volMin);
   lots = MathMin(lots, volMax);
   int steps = (int)MathRound(lots / volStep);
   return steps * volStep;
}

//+------------------------------------------------------------------+
//| Open Buy                                                         |
//+------------------------------------------------------------------+
void OpenBuy(double lots, double sl, double tp)
{
   trade.SetExpertMagicNumber(MagicNumber);
   if(!trade.Buy(lots, _Symbol, 0.0, sl, tp, "SuperTrendRSI Buy"))
      Print("Buy failed: ", GetLastError());
}

//+------------------------------------------------------------------+
//| Open Sell                                                        |
//+------------------------------------------------------------------+
void OpenSell(double lots, double sl, double tp)
{
   trade.SetExpertMagicNumber(MagicNumber);
   if(!trade.Sell(lots, _Symbol, 0.0, sl, tp, "SuperTrendRSI Sell"))
      Print("Sell failed: ", GetLastError());
}

//+------------------------------------------------------------------+
//| Manage Positions                                                 |
//+------------------------------------------------------------------+
void ManagePositions(bool wantBuy, bool wantSell)
{
   int total = PositionsTotal();
   for(int i = total - 1; i >= 0; i--)
   {
      if(!PositionSelectByIndex(i)) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;

      long ptype   = PositionGetInteger(POSITION_TYPE);
      double psl   = PositionGetDouble(POSITION_SL);
      double ptp   = PositionGetDouble(POSITION_TP);
      double popen = PositionGetDouble(POSITION_PRICE_OPEN);

      // close on opposite signals
      if(ptype == POSITION_TYPE_BUY && wantSell)
      {
         if(!trade.PositionClose(_Symbol))
            Print("Close BUY failed: ", GetLastError());
         continue;
      }
      if(ptype == POSITION_TYPE_SELL && wantBuy)
      {
         if(!trade.PositionClose(_Symbol))
            Print("Close SELL failed: ", GetLastError());
         continue;
      }

      // trailing stop
      if(UseTrailing)
      {
         double current = (ptype == POSITION_TYPE_BUY)
                          ? SymbolInfoDouble(_Symbol, SYMBOL_BID)
                          : SymbolInfoDouble(_Symbol, SYMBOL_ASK);

         double profitPoints = (ptype == POSITION_TYPE_BUY)
                               ? (current - popen) / _Point
                               : (popen - current) / _Point;

         if(profitPoints > TrailingStartPoints)
         {
            double newSL = (ptype == POSITION_TYPE_BUY)
                           ? (current - TrailingStepPoints * _Point)
                           : (current + TrailingStepPoints * _Point);

            if((ptype == POSITION_TYPE_BUY && (psl < newSL || psl == 0.0)) ||
               (ptype == POSITION_TYPE_SELL && (psl > newSL || psl == 0.0)))
            {
               if(!trade.PositionModify(_Symbol, 0.0, newSL, ptp))
                  Print("PositionModify failed: ", GetLastError());
            }
         }
      }
   }
}

//+------------------------------------------------------------------+
//| OnTick                                                           |
//+------------------------------------------------------------------+
void OnTick()
{
   if(Bars(_Symbol, _Period) < MathMax(ATR_Period, RSI_Period) + 5) return;

   bool trendUp = true;
   double stValue = 0.0;
   ComputeSuperTrend(trendUp, stValue);

   bool rsiBuy  = RSI_BuyCondition();
   bool rsiSell = RSI_SellCondition();

   bool wantBuy  = (trendUp && rsiBuy && AllowBuy);
   bool wantSell = (!trendUp && rsiSell && AllowSell);

   ManagePositions(wantBuy, wantSell);

   bool haveBuy = false, haveSell = false;
   int posTotal = PositionsTotal();
   for(int i = posTotal - 1; i >= 0; i--)
   {
      if(!PositionSelectByIndex(i)) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ulong)PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;

      long ptype = PositionGetInteger(POSITION_TYPE);
      if(ptype == POSITION_TYPE_BUY)  haveBuy = true;
      if(ptype == POSITION_TYPE_SELL) haveSell = true;
   }

   double lots = UseFixedLots ? FixedLots : (AccountInfoDouble(ACCOUNT_BALANCE) * LotsFactor);
   lots = NormalizeVolume(lots);

   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   // buy entry
   if(wantBuy && !haveBuy)
   {
      double sl_price = 0.0, tp_price = 0.0;
      if(FixedStopLoss_Pips > 0.0)
         sl_price = NormalizeDouble(ask - FixedStopLoss_Pips * _Point, (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS));
      else if(stValue > 0.0 && stValue < ask)
         sl_price = NormalizeDouble(stValue, (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS));

      if(TakeProfit_Pips > 0.0)
         tp_price = NormalizeDouble(ask + TakeProfit_Pips * _Point, (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS));

      OpenBuy(lots, sl_price, tp_price);
   }

   // sell entry
   if(wantSell && !haveSell)
   {
      double sl_price = 0.0, tp_price = 0.0;
      if(FixedStopLoss_Pips > 0.0)
         sl_price = NormalizeDouble(bid + FixedStopLoss_Pips * _Point, (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS));
      else if(stValue > 0.0 && stValue > bid)
         sl_price = NormalizeDouble(stValue, (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS));

      if(TakeProfit_Pips > 0.0)
         tp_price = NormalizeDouble(bid - TakeProfit_Pips * _Point, (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS));

      OpenSell(lots, sl_price, tp_price);
   }
}
//+------------------------------------------------------------------+
